const sequences = [
    {
        "name": "2pattern_0_V10_A067.mid",
        "valence": 6,
        "arousal": 5,
        "sequence": [
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            46,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41
        ]
    },
    {
        "name": "pattern_0_V067_A-10.mid",
        "valence": 5,
        "arousal": 0,
        "sequence": [
            56,
            51,
            0,
            51,
            0,
            56,
            56,
            0,
            51,
            51,
            56,
            51,
            0,
            51,
            51,
            0
        ]
    },
    {
        "name": "pattern_0_V-067_A00.mid",
        "valence": 1,
        "arousal": 3,
        "sequence": [
            44,
            0,
            0,
            0,
            60,
            60,
            0,
            44,
            0,
            0,
            44,
            0,
            0,
            46,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V10_A10.mid",
        "valence": 6,
        "arousal": 6,
        "sequence": [
            51,
            51,
            56,
            56,
            56,
            56,
            60,
            74,
            51,
            74,
            70,
            55,
            55,
            58,
            55,
            55
        ]
    },
    {
        "name": "3pattern__0_V00_A-033.mid",
        "valence": "",
        "arousal": 3,
        "sequence": [
            70,
            70,
            70,
            53,
            70,
            70,
            70,
            70,
            70,
            70,
            70,
            70,
            70,
            70,
            70,
            70
        ]
    },
    {
        "name": "2pattern_0_V067_A-033.mid",
        "valence": 5,
        "arousal": 2,
        "sequence": [
            79,
            0,
            67,
            65,
            0,
            0,
            64,
            0,
            62,
            62,
            0,
            62,
            0,
            61,
            57,
            59
        ]
    },
    {
        "name": "2pattern_0_V-10_A00.mid",
        "valence": 0,
        "arousal": 3,
        "sequence": [
            45,
            0,
            0,
            44,
            0,
            42,
            52,
            40,
            40,
            40,
            45,
            40,
            54,
            42,
            40,
            42
        ]
    },
    {
        "name": "2pattern_0_V-067_A10.mid",
        "valence": 1,
        "arousal": 6,
        "sequence": [
            50,
            0,
            38,
            50,
            38,
            38,
            50,
            48,
            50,
            69,
            47,
            47,
            62,
            0,
            43,
            55
        ]
    },
    {
        "name": "3pattern__0_V-067_A033.mid",
        "valence": "",
        "arousal": 1,
        "sequence": [
            53,
            58,
            53,
            53,
            53,
            53,
            46,
            53,
            53,
            46,
            53,
            53,
            46,
            53,
            53,
            53
        ]
    },
    {
        "name": "2pattern_0_V-033_A033.mid",
        "valence": 2,
        "arousal": 4,
        "sequence": [
            33,
            33,
            33,
            33,
            33,
            35,
            35,
            35,
            32,
            30,
            32,
            33,
            0,
            33,
            0,
            33
        ]
    },
    {
        "name": "3pattern__0_V-033_A-067.mid",
        "valence": "",
        "arousal": 2,
        "sequence": [
            71,
            71,
            71,
            69,
            69,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "3pattern__0_V00_A-10.mid",
        "valence": "",
        "arousal": 3,
        "sequence": [
            63,
            0,
            0,
            0,
            0,
            0,
            63,
            0,
            0,
            0,
            0,
            0,
            0,
            66,
            0,
            0
        ]
    },
    {
        "name": "3pattern__0_V-067_A-067.mid",
        "valence": "",
        "arousal": 1,
        "sequence": [
            59,
            62,
            0,
            59,
            0,
            62,
            0,
            59,
            59,
            62,
            59,
            0,
            59,
            0,
            55,
            0
        ]
    },
    {
        "name": "2pattern_0_V10_A-10.mid",
        "valence": 6,
        "arousal": 0,
        "sequence": [
            51,
            0,
            51,
            0,
            0,
            55,
            65,
            0,
            62,
            67,
            62,
            0,
            62,
            70,
            0,
            62
        ]
    },
    {
        "name": "3pattern__0_V10_A067.mid",
        "valence": "",
        "arousal": 6,
        "sequence": [
            42,
            57,
            42,
            42,
            42,
            45,
            0,
            54,
            50,
            55,
            62,
            55,
            55,
            55,
            55,
            55
        ]
    },
    {
        "name": "pattern_0_V00_A00.mid",
        "valence": 3,
        "arousal": 3,
        "sequence": [
            67,
            64,
            64,
            60,
            60,
            60,
            60,
            60,
            53,
            53,
            55,
            55,
            60,
            60,
            60,
            60
        ]
    },
    {
        "name": "pattern_0_V10_A033.mid",
        "valence": 6,
        "arousal": 4,
        "sequence": [
            57,
            0,
            57,
            57,
            57,
            57,
            57,
            0,
            0,
            66,
            62,
            62,
            62,
            62,
            62,
            62
        ]
    },
    {
        "name": "pattern_0_V-067_A-067.mid",
        "valence": 1,
        "arousal": 1,
        "sequence": [
            62,
            67,
            0,
            62,
            0,
            67,
            0,
            62,
            0,
            53,
            0,
            60,
            65,
            53,
            60,
            0
        ]
    },
    {
        "name": "3pattern__0_V-033_A10.mid",
        "valence": "",
        "arousal": 2,
        "sequence": [
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            48,
            43,
            43,
            43,
            43,
            43,
            43,
            43
        ]
    },
    {
        "name": "3pattern__0_V00_A-067.mid",
        "valence": "",
        "arousal": 3,
        "sequence": [
            57,
            0,
            0,
            61,
            0,
            0,
            0,
            57,
            0,
            0,
            57,
            0,
            0,
            0,
            57,
            0
        ]
    },
    {
        "name": "2pattern_0_V00_A-10.mid",
        "valence": 3,
        "arousal": 0,
        "sequence": [
            63,
            63,
            0,
            63,
            0,
            0,
            63,
            61,
            0,
            49,
            49,
            0,
            54,
            0,
            0,
            58
        ]
    },
    {
        "name": "2pattern_0_V-067_A00.mid",
        "valence": 1,
        "arousal": 3,
        "sequence": [
            53,
            53,
            53,
            53,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            58,
            61,
            61,
            61,
            61
        ]
    },
    {
        "name": "2pattern_0_V-10_A-10.mid",
        "valence": 0,
        "arousal": 0,
        "sequence": [
            65,
            0,
            0,
            63,
            0,
            0,
            70,
            0,
            0,
            0,
            0,
            75,
            0,
            0,
            75,
            0
        ]
    },
    {
        "name": "2pattern_0_V067_A00.mid",
        "valence": 5,
        "arousal": 3,
        "sequence": [
            69,
            69,
            0,
            0,
            64,
            64,
            57,
            57,
            57,
            57,
            57,
            57,
            0,
            0,
            66,
            62
        ]
    },
    {
        "name": "3pattern__0_V067_A-10.mid",
        "valence": "",
        "arousal": 5,
        "sequence": [
            45,
            0,
            0,
            45,
            0,
            45,
            0,
            44,
            0,
            0,
            44,
            0,
            44,
            0,
            42,
            0
        ]
    },
    {
        "name": "2pattern_0_V00_A-033.mid",
        "valence": 3,
        "arousal": 2,
        "sequence": [
            60,
            62,
            60,
            55,
            60,
            55,
            62,
            55,
            55,
            63,
            60,
            63,
            60,
            67,
            60,
            0
        ]
    },
    {
        "name": "pattern_0_V033_A033.mid",
        "valence": 4,
        "arousal": 4,
        "sequence": [
            57,
            57,
            57,
            57,
            57,
            57,
            57,
            57,
            57,
            57,
            0,
            50,
            50,
            0,
            50,
            57
        ]
    },
    {
        "name": "3pattern__0_V-10_A00.mid",
        "valence": "",
        "arousal": 0,
        "sequence": [
            32,
            44,
            44,
            0,
            32,
            44,
            44,
            32,
            32,
            44,
            44,
            32,
            32,
            44,
            32,
            32
        ]
    },
    {
        "name": "pattern_0_V10_A-10.mid",
        "valence": 6,
        "arousal": 0,
        "sequence": [
            60,
            57,
            60,
            62,
            0,
            57,
            0,
            0,
            0,
            0,
            0,
            55,
            0,
            50,
            0,
            0
        ]
    },
    {
        "name": "3pattern__0_V10_A-10.mid",
        "valence": "",
        "arousal": 6,
        "sequence": [
            40,
            40,
            47,
            0,
            52,
            55,
            0,
            0,
            0,
            0,
            42,
            0,
            42,
            49,
            64,
            0
        ]
    },
    {
        "name": "pattern_0_V033_A10.mid",
        "valence": 4,
        "arousal": 6,
        "sequence": [
            29,
            27,
            27,
            27,
            0,
            27,
            27,
            27,
            27,
            27,
            27,
            27,
            27,
            27,
            39,
            27
        ]
    },
    {
        "name": "2pattern_0_V-033_A10.mid",
        "valence": 2,
        "arousal": 6,
        "sequence": [
            61,
            59,
            56,
            49,
            61,
            59,
            56,
            73,
            66,
            63,
            68,
            66,
            70,
            63,
            47,
            52
        ]
    },
    {
        "name": "3pattern__0_V00_A033.mid",
        "valence": "",
        "arousal": 3,
        "sequence": [
            69,
            0,
            0,
            72,
            62,
            0,
            0,
            65,
            0,
            0,
            0,
            0,
            62,
            62,
            63,
            70
        ]
    },
    {
        "name": "2pattern_0_V-067_A033.mid",
        "valence": 1,
        "arousal": 4,
        "sequence": [
            41,
            41,
            41,
            41,
            53,
            53,
            53,
            53,
            48,
            48,
            56,
            56,
            56,
            53,
            56,
            53
        ]
    },
    {
        "name": "3pattern__0_V-033_A033.mid",
        "valence": "",
        "arousal": 2,
        "sequence": [
            30,
            30,
            30,
            30,
            0,
            35,
            35,
            0,
            30,
            30,
            30,
            30,
            30,
            30,
            30,
            30
        ]
    },
    {
        "name": "pattern_0_V-033_A-033.mid",
        "valence": 2,
        "arousal": 2,
        "sequence": [
            43,
            0,
            36,
            60,
            60,
            43,
            60,
            60,
            36,
            0,
            67,
            60,
            76,
            60,
            0,
            67
        ]
    },
    {
        "name": "2pattern_0_V-10_A-033.mid",
        "valence": 0,
        "arousal": 2,
        "sequence": [
            46,
            0,
            0,
            0,
            0,
            53,
            0,
            63,
            0,
            0,
            0,
            0,
            37,
            37,
            37,
            0
        ]
    },
    {
        "name": "2pattern_0_V033_A-033.mid",
        "valence": 4,
        "arousal": 2,
        "sequence": [
            67,
            68,
            70,
            0,
            72,
            70,
            73,
            72,
            70,
            0,
            73,
            72,
            51,
            0,
            0,
            70
        ]
    },
    {
        "name": "2pattern_0_V067_A-067.mid",
        "valence": 5,
        "arousal": 1,
        "sequence": [
            65,
            64,
            65,
            0,
            0,
            64,
            58,
            60,
            62,
            62,
            62,
            0,
            60,
            62,
            62,
            60
        ]
    },
    {
        "name": "pattern_0_V00_A-10.mid",
        "valence": 3,
        "arousal": 0,
        "sequence": [
            45,
            0,
            0,
            0,
            0,
            0,
            43,
            0,
            0,
            0,
            0,
            0,
            41,
            0,
            0,
            0
        ]
    },
    {
        "name": "2pattern_0_V10_A-033.mid",
        "valence": 6,
        "arousal": 2,
        "sequence": [
            55,
            60,
            55,
            55,
            55,
            55,
            60,
            55,
            55,
            55,
            55,
            60,
            55,
            55,
            55,
            55
        ]
    },
    {
        "name": "3pattern__0_V10_A-033.mid",
        "valence": "",
        "arousal": 6,
        "sequence": [
            62,
            0,
            0,
            0,
            58,
            0,
            57,
            0,
            57,
            0,
            57,
            57,
            57,
            57,
            57,
            57
        ]
    },
    {
        "name": "2pattern_0_V-10_A10.mid",
        "valence": 0,
        "arousal": 6,
        "sequence": [
            77,
            77,
            81,
            74,
            82,
            82,
            65,
            65,
            65,
            65,
            65,
            69,
            69,
            72,
            69,
            72
        ]
    },
    {
        "name": "pattern_0_V033_A00.mid",
        "valence": 4,
        "arousal": 3,
        "sequence": [
            60,
            0,
            60,
            0,
            0,
            60,
            0,
            60,
            60,
            60,
            60,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V10_A067.mid",
        "valence": 6,
        "arousal": 5,
        "sequence": [
            61,
            56,
            47,
            56,
            56,
            56,
            56,
            56,
            57,
            57,
            57,
            57,
            57,
            56,
            56,
            56
        ]
    },
    {
        "name": "pattern_0_V033_A067.mid",
        "valence": 4,
        "arousal": 5,
        "sequence": [
            55,
            52,
            52,
            52,
            50,
            50,
            50,
            50,
            0,
            50,
            50,
            60,
            55,
            52,
            52,
            52
        ]
    },
    {
        "name": "3pattern__0_V10_A033.mid",
        "valence": "",
        "arousal": 6,
        "sequence": [
            63,
            63,
            63,
            63,
            68,
            63,
            63,
            61,
            61,
            61,
            61,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "2pattern_0_V00_A-067.mid",
        "valence": 3,
        "arousal": 1,
        "sequence": [
            36,
            48,
            36,
            48,
            34,
            46,
            34,
            46,
            31,
            43,
            43,
            36,
            48,
            34,
            46,
            34
        ]
    },
    {
        "name": "2pattern_0_V00_A067.mid",
        "valence": 3,
        "arousal": 5,
        "sequence": [
            29,
            29,
            29,
            29,
            34,
            34,
            34,
            0,
            41,
            41,
            29,
            41,
            41,
            41,
            22,
            34
        ]
    },
    {
        "name": "2pattern_0_V-067_A-033.mid",
        "valence": 1,
        "arousal": 2,
        "sequence": [
            53,
            0,
            53,
            66,
            53,
            53,
            53,
            0,
            0,
            53,
            0,
            53,
            0,
            0,
            0,
            61
        ]
    },
    {
        "name": "3pattern__0_V067_A033.mid",
        "valence": "",
        "arousal": 5,
        "sequence": [
            41,
            41,
            41,
            41,
            41,
            41,
            44,
            0,
            44,
            44,
            44,
            44,
            44,
            51,
            51,
            51
        ]
    },
    {
        "name": "2pattern_0_V00_A033.mid",
        "valence": 3,
        "arousal": 4,
        "sequence": [
            57,
            59,
            59,
            62,
            62,
            60,
            60,
            60,
            60,
            60,
            67,
            67,
            67,
            67,
            67,
            67
        ]
    },
    {
        "name": "2pattern_0_V-067_A067.mid",
        "valence": 1,
        "arousal": 5,
        "sequence": [
            74,
            74,
            77,
            74,
            74,
            74,
            74,
            74,
            74,
            72,
            72,
            77,
            77,
            77,
            72,
            72
        ]
    },
    {
        "name": "pattern_0_V033_A-067.mid",
        "valence": 4,
        "arousal": 1,
        "sequence": [
            57,
            0,
            0,
            0,
            0,
            70,
            72,
            0,
            0,
            69,
            67,
            0,
            57,
            67,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V-067_A033.mid",
        "valence": 1,
        "arousal": 4,
        "sequence": [
            31,
            31,
            29,
            29,
            43,
            31,
            43,
            31,
            29,
            0,
            68,
            71,
            66,
            0,
            71,
            0
        ]
    },
    {
        "name": "3pattern__0_V-067_A-10.mid",
        "valence": "",
        "arousal": 1,
        "sequence": [
            37,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            39,
            0,
            0,
            0,
            0,
            39,
            63
        ]
    },
    {
        "name": "pattern_0_V-033_A033.mid",
        "valence": 2,
        "arousal": 4,
        "sequence": [
            44,
            51,
            51,
            44,
            51,
            44,
            0,
            44,
            63,
            51,
            63,
            71,
            71,
            71,
            59,
            49
        ]
    },
    {
        "name": "pattern_0_V00_A10.mid",
        "valence": 3,
        "arousal": 6,
        "sequence": [
            56,
            56,
            56,
            56,
            56,
            60,
            56,
            60,
            58,
            58,
            62,
            62,
            62,
            67,
            63,
            63
        ]
    },
    {
        "name": "2pattern_0_V00_A10.mid",
        "valence": 3,
        "arousal": 6,
        "sequence": [
            60,
            60,
            60,
            65,
            0,
            0,
            63,
            65,
            65,
            70,
            65,
            77,
            73,
            0,
            72,
            70
        ]
    },
    {
        "name": "pattern_0_V-10_A033.mid",
        "valence": 0,
        "arousal": 4,
        "sequence": [
            32,
            32,
            32,
            32,
            32,
            32,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "2pattern_0_V033_A10.mid",
        "valence": 4,
        "arousal": 6,
        "sequence": [
            64,
            64,
            64,
            67,
            62,
            62,
            67,
            62,
            67,
            62,
            57,
            62,
            62,
            50,
            66,
            54
        ]
    },
    {
        "name": "3pattern__0_V-10_A10.mid",
        "valence": "",
        "arousal": 0,
        "sequence": [
            64,
            0,
            62,
            59,
            52,
            52,
            52,
            52,
            52,
            52,
            47,
            52,
            51,
            52,
            52,
            51
        ]
    },
    {
        "name": "3pattern__0_V067_A-067.mid",
        "valence": "",
        "arousal": 5,
        "sequence": [
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            34,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V033_A-033.mid",
        "valence": 4,
        "arousal": 2,
        "sequence": [
            57,
            53,
            53,
            53,
            53,
            53,
            53,
            53,
            53,
            53,
            53,
            53,
            53,
            53,
            38,
            38
        ]
    },
    {
        "name": "3pattern__0_V033_A-033.mid",
        "valence": "",
        "arousal": 4,
        "sequence": [
            57,
            57,
            57,
            57,
            57,
            57,
            0,
            57,
            0,
            57,
            0,
            57,
            0,
            57,
            57,
            57
        ]
    },
    {
        "name": "2pattern_0_V033_A033.mid",
        "valence": 4,
        "arousal": 4,
        "sequence": [
            49,
            56,
            56,
            56,
            49,
            56,
            56,
            49,
            49,
            56,
            49,
            49,
            49,
            49,
            44,
            44
        ]
    },
    {
        "name": "2pattern_0_V-10_A-067.mid",
        "valence": 0,
        "arousal": 1,
        "sequence": [
            52,
            59,
            52,
            0,
            59,
            52,
            40,
            40,
            40,
            52,
            59,
            52,
            47,
            35,
            47,
            51
        ]
    },
    {
        "name": "3pattern__0_V-10_A033.mid",
        "valence": "",
        "arousal": 0,
        "sequence": [
            72,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "2pattern_0_V033_A-067.mid",
        "valence": 4,
        "arousal": 1,
        "sequence": [
            66,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            51,
            58,
            63,
            66,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "2pattern_0_V033_A00.mid",
        "valence": 4,
        "arousal": 3,
        "sequence": [
            40,
            40,
            40,
            47,
            40,
            40,
            40,
            40,
            47,
            40,
            40,
            40,
            40,
            40,
            40,
            40
        ]
    },
    {
        "name": "pattern_0_V-033_A-10.mid",
        "valence": 2,
        "arousal": 0,
        "sequence": [
            61,
            62,
            57,
            0,
            61,
            57,
            57,
            0,
            62,
            57,
            0,
            57,
            62,
            57,
            0,
            62
        ]
    },
    {
        "name": "pattern_0_V067_A-033.mid",
        "valence": 5,
        "arousal": 2,
        "sequence": [
            47,
            47,
            62,
            62,
            43,
            43,
            43,
            0,
            43,
            0,
            50,
            0,
            50,
            0,
            50,
            0
        ]
    },
    {
        "name": "pattern_0_V067_A067.mid",
        "valence": 5,
        "arousal": 5,
        "sequence": [
            62,
            65,
            62,
            60,
            62,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            0,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V00_A067.mid",
        "valence": 3,
        "arousal": 5,
        "sequence": [
            31,
            38,
            39,
            39,
            39,
            39,
            39,
            39,
            39,
            68,
            39,
            39,
            39,
            39,
            39,
            39
        ]
    },
    {
        "name": "pattern_0_V067_A10.mid",
        "valence": 5,
        "arousal": 6,
        "sequence": [
            63,
            67,
            70,
            0,
            63,
            67,
            0,
            58,
            58,
            58,
            58,
            58,
            55,
            55,
            58,
            55
        ]
    },
    {
        "name": "2pattern_0_V10_A-067.mid",
        "valence": 6,
        "arousal": 1,
        "sequence": [
            55,
            59,
            64,
            57,
            57,
            55,
            55,
            59,
            55,
            57,
            60,
            57,
            59,
            62,
            59,
            60
        ]
    },
    {
        "name": "3pattern__0_V-033_A-033.mid",
        "valence": "",
        "arousal": 2,
        "sequence": [
            61,
            61,
            56,
            0,
            0,
            68,
            68,
            58,
            51,
            0,
            0,
            0,
            0,
            0,
            51,
            58
        ]
    },
    {
        "name": "2pattern_0_V-067_A-067.mid",
        "valence": 1,
        "arousal": 1,
        "sequence": [
            54,
            54,
            54,
            57,
            54,
            0,
            55,
            50,
            0,
            55,
            50,
            0,
            54,
            50,
            0,
            54
        ]
    },
    {
        "name": "pattern_0_V067_A00.mid",
        "valence": 5,
        "arousal": 3,
        "sequence": [
            54,
            42,
            42,
            54,
            54,
            47,
            0,
            51,
            51,
            54,
            54,
            59,
            47,
            59,
            54,
            59
        ]
    },
    {
        "name": "pattern_0_V-067_A067.mid",
        "valence": 1,
        "arousal": 5,
        "sequence": [
            49,
            42,
            42,
            42,
            42,
            42,
            45,
            45,
            45,
            45,
            45,
            45,
            0,
            45,
            45,
            45
        ]
    },
    {
        "name": "2pattern_0_V033_A-10.mid",
        "valence": 4,
        "arousal": 0,
        "sequence": [
            34,
            37,
            0,
            0,
            34,
            0,
            0,
            0,
            0,
            37,
            0,
            0,
            0,
            0,
            37,
            0
        ]
    },
    {
        "name": "3pattern__0_V-067_A00.mid",
        "valence": "",
        "arousal": 1,
        "sequence": [
            36,
            36,
            36,
            36,
            36,
            31,
            31,
            34,
            34,
            31,
            31,
            34,
            31,
            31,
            36,
            34
        ]
    },
    {
        "name": "pattern_0_V-067_A10.mid",
        "valence": 1,
        "arousal": 6,
        "sequence": [
            50,
            50,
            36,
            48,
            36,
            48,
            48,
            48,
            48,
            36,
            36,
            48,
            36,
            62,
            62,
            55
        ]
    },
    {
        "name": "2pattern_0_V-067_A-10.mid",
        "valence": 1,
        "arousal": 0,
        "sequence": [
            63,
            63,
            71,
            0,
            73,
            63,
            0,
            63,
            77,
            63,
            63,
            0,
            70,
            63,
            89,
            0
        ]
    },
    {
        "name": "3pattern__0_V067_A-033.mid",
        "valence": "",
        "arousal": 5,
        "sequence": [
            43,
            43,
            43,
            43,
            41,
            43,
            46,
            46,
            48,
            48,
            46,
            46,
            44,
            46,
            46,
            44
        ]
    },
    {
        "name": "2pattern_0_V-033_A-10.mid",
        "valence": 2,
        "arousal": 0,
        "sequence": [
            54,
            0,
            0,
            0,
            0,
            0,
            51,
            0,
            0,
            0,
            0,
            0,
            0,
            51,
            0,
            0
        ]
    },
    {
        "name": "3pattern__0_V-10_A-10.mid",
        "valence": "",
        "arousal": 0,
        "sequence": [
            63,
            58,
            0,
            58,
            0,
            62,
            0,
            58,
            0,
            58,
            0,
            58,
            45,
            0,
            45,
            0
        ]
    },
    {
        "name": "pattern_0_V00_A-033.mid",
        "valence": 3,
        "arousal": 2,
        "sequence": [
            66,
            64,
            61,
            78,
            66,
            57,
            64,
            61,
            69,
            57,
            57,
            54,
            57,
            54,
            0,
            59
        ]
    },
    {
        "name": "3pattern__0_V033_A00.mid",
        "valence": "",
        "arousal": 4,
        "sequence": [
            57,
            59,
            0,
            57,
            0,
            0,
            0,
            0,
            0,
            0,
            51,
            0,
            54,
            51,
            0,
            0
        ]
    },
    {
        "name": "3pattern__0_V10_A00.mid",
        "valence": "",
        "arousal": 6,
        "sequence": [
            42,
            0,
            0,
            42,
            58,
            58,
            58,
            58,
            58,
            56,
            56,
            56,
            56,
            56,
            56,
            56
        ]
    },
    {
        "name": "2pattern_0_V067_A10.mid",
        "valence": 5,
        "arousal": 6,
        "sequence": [
            48,
            48,
            48,
            48,
            48,
            48,
            53,
            53,
            53,
            53,
            53,
            72,
            0,
            72,
            79,
            81
        ]
    },
    {
        "name": "pattern_0_V-10_A00.mid",
        "valence": 0,
        "arousal": 3,
        "sequence": [
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            0,
            45,
            45,
            52,
            52,
            52
        ]
    },
    {
        "name": "3pattern__0_V033_A10.mid",
        "valence": "",
        "arousal": 4,
        "sequence": [
            70,
            70,
            70,
            70,
            70,
            68,
            68,
            68,
            56,
            56,
            56,
            56,
            56,
            56,
            56,
            56
        ]
    },
    {
        "name": "3pattern__0_V-033_A067.mid",
        "valence": "",
        "arousal": 2,
        "sequence": [
            40,
            40,
            40,
            45,
            45,
            0,
            40,
            45,
            33,
            33,
            33,
            40,
            33,
            33,
            35,
            33
        ]
    },
    {
        "name": "pattern_0_V10_A-033.mid",
        "valence": 6,
        "arousal": 2,
        "sequence": [
            41,
            44,
            41,
            41,
            45,
            46,
            49,
            45,
            46,
            51,
            39,
            46,
            34,
            36,
            39,
            34
        ]
    },
    {
        "name": "3pattern__0_V033_A033.mid",
        "valence": "",
        "arousal": 4,
        "sequence": [
            32,
            32,
            32,
            32,
            0,
            0,
            25,
            25,
            25,
            25,
            0,
            25,
            28,
            30,
            30,
            42
        ]
    },
    {
        "name": "3pattern__0_V067_A10.mid",
        "valence": "",
        "arousal": 5,
        "sequence": [
            71,
            71,
            68,
            68,
            71,
            52,
            76,
            52,
            52,
            52,
            52,
            52,
            52,
            52,
            52,
            54
        ]
    },
    {
        "name": "3pattern__0_V-10_A067.mid",
        "valence": "",
        "arousal": 0,
        "sequence": [
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33
        ]
    },
    {
        "name": "2pattern_0_V10_A00.mid",
        "valence": 6,
        "arousal": 3,
        "sequence": [
            43,
            50,
            43,
            43,
            50,
            43,
            43,
            43,
            50,
            43,
            43,
            43,
            43,
            43,
            50,
            50
        ]
    },
    {
        "name": "pattern_0_V-10_A-067.mid",
        "valence": 0,
        "arousal": 1,
        "sequence": [
            68,
            0,
            73,
            68,
            73,
            64,
            68,
            73,
            64,
            68,
            73,
            64,
            68,
            64,
            64,
            68
        ]
    },
    {
        "name": "pattern_0_V-033_A00.mid",
        "valence": 2,
        "arousal": 3,
        "sequence": [
            60,
            0,
            64,
            60,
            65,
            65,
            65,
            67,
            65,
            70,
            70,
            67,
            67,
            67,
            67,
            70
        ]
    },
    {
        "name": "3pattern__0_V033_A-067.mid",
        "valence": "",
        "arousal": 4,
        "sequence": [
            45,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            45,
            0,
            0,
            0,
            0,
            41
        ]
    },
    {
        "name": "pattern_0_V-033_A-067.mid",
        "valence": 2,
        "arousal": 1,
        "sequence": [
            63,
            0,
            0,
            0,
            75,
            0,
            73,
            0,
            71,
            54,
            0,
            0,
            63,
            58,
            0,
            73
        ]
    },
    {
        "name": "2pattern_0_V10_A033.mid",
        "valence": 6,
        "arousal": 4,
        "sequence": [
            54,
            54,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            57,
            61,
            61
        ]
    },
    {
        "name": "3pattern__0_V033_A-10.mid",
        "valence": "",
        "arousal": 4,
        "sequence": [
            58,
            65,
            62,
            0,
            63,
            62,
            39,
            0,
            55,
            39,
            0,
            53,
            55,
            39,
            53,
            51
        ]
    },
    {
        "name": "2pattern_0_V10_A10.mid",
        "valence": 6,
        "arousal": 6,
        "sequence": [
            53,
            55,
            0,
            56,
            55,
            56,
            56,
            56,
            56,
            56,
            56,
            60,
            53,
            63,
            63,
            53
        ]
    },
    {
        "name": "pattern_0_V-033_A10.mid",
        "valence": 2,
        "arousal": 6,
        "sequence": [
            42,
            42,
            42,
            42,
            42,
            42,
            42,
            42,
            66,
            45,
            45,
            47,
            56,
            59,
            56,
            54
        ]
    },
    {
        "name": "2pattern_0_V-033_A-067.mid",
        "valence": 2,
        "arousal": 1,
        "sequence": [
            67,
            58,
            0,
            58,
            58,
            58,
            62,
            57,
            60,
            0,
            65,
            0,
            0,
            0,
            0,
            69
        ]
    },
    {
        "name": "3pattern__0_V10_A10.mid",
        "valence": "",
        "arousal": 6,
        "sequence": [
            56,
            56,
            59,
            57,
            57,
            56,
            52,
            52,
            47,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V-10_A10.mid",
        "valence": 0,
        "arousal": 6,
        "sequence": [
            47,
            47,
            47,
            47,
            52,
            52,
            52,
            52,
            52,
            52,
            52,
            52,
            52,
            52,
            52,
            52
        ]
    },
    {
        "name": "2pattern_0_V067_A-10.mid",
        "valence": 5,
        "arousal": 0,
        "sequence": [
            33,
            33,
            33,
            0,
            33,
            45,
            33,
            33,
            45,
            28,
            28,
            40,
            40,
            40,
            28,
            28
        ]
    },
    {
        "name": "pattern_0_V067_A033.mid",
        "valence": 5,
        "arousal": 4,
        "sequence": [
            44,
            44,
            0,
            44,
            56,
            44,
            44,
            44,
            44,
            44,
            44,
            49,
            49,
            49,
            47,
            47
        ]
    },
    {
        "name": "2pattern_0_V-033_A067.mid",
        "valence": 2,
        "arousal": 5,
        "sequence": [
            55,
            55,
            55,
            60,
            64,
            67,
            64,
            64,
            0,
            0,
            0,
            0,
            0,
            60,
            55,
            60
        ]
    },
    {
        "name": "3pattern__0_V-10_A-033.mid",
        "valence": "",
        "arousal": 0,
        "sequence": [
            55,
            55,
            59,
            62,
            59,
            59,
            62,
            62,
            59,
            59,
            59,
            59,
            59,
            59,
            59,
            59
        ]
    },
    {
        "name": "pattern_0_V00_A-067.mid",
        "valence": 3,
        "arousal": 1,
        "sequence": [
            52,
            0,
            0,
            0,
            0,
            59,
            0,
            52,
            59,
            0,
            52,
            54,
            0,
            59,
            0,
            0
        ]
    },
    {
        "name": "2pattern_0_V033_A067.mid",
        "valence": 4,
        "arousal": 5,
        "sequence": [
            51,
            51,
            51,
            51,
            51,
            51,
            51,
            51,
            51,
            58,
            51,
            51,
            51,
            51,
            51,
            51
        ]
    },
    {
        "name": "2pattern_0_V-033_A-033.mid",
        "valence": 2,
        "arousal": 2,
        "sequence": [
            64,
            0,
            64,
            66,
            64,
            62,
            59,
            0,
            62,
            59,
            60,
            57,
            64,
            66,
            64,
            62
        ]
    },
    {
        "name": "3pattern__0_V033_A067.mid",
        "valence": "",
        "arousal": 4,
        "sequence": [
            48,
            48,
            55,
            48,
            55,
            48,
            55,
            48,
            55,
            55,
            48,
            55,
            48,
            55,
            48,
            55
        ]
    },
    {
        "name": "pattern_0_V-067_A-10.mid",
        "valence": 1,
        "arousal": 0,
        "sequence": [
            46,
            0,
            0,
            0,
            0,
            0,
            53,
            53,
            60,
            0,
            60,
            0,
            50,
            0,
            0,
            0
        ]
    },
    {
        "name": "3pattern__0_V-033_A-10.mid",
        "valence": "",
        "arousal": 2,
        "sequence": [
            59,
            59,
            0,
            59,
            0,
            0,
            0,
            59,
            0,
            0,
            0,
            59,
            0,
            0,
            0,
            59
        ]
    },
    {
        "name": "3pattern__0_V00_A00.mid",
        "valence": "",
        "arousal": 3,
        "sequence": [
            39,
            42,
            42,
            44,
            44,
            44,
            44,
            44,
            46,
            46,
            46,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "2pattern_0_V067_A033.mid",
        "valence": 5,
        "arousal": 4,
        "sequence": [
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            0,
            41,
            0,
            0,
            0
        ]
    },
    {
        "name": "3pattern__0_V-067_A10.mid",
        "valence": "",
        "arousal": 1,
        "sequence": [
            63,
            63,
            63,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            60
        ]
    },
    {
        "name": "pattern_0_V00_A033.mid",
        "valence": 3,
        "arousal": 4,
        "sequence": [
            40,
            26,
            28,
            28,
            40,
            40,
            38,
            50,
            38,
            26,
            26,
            38,
            38,
            38,
            38,
            33
        ]
    },
    {
        "name": "3pattern__0_V00_A10.mid",
        "valence": "",
        "arousal": 3,
        "sequence": [
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            0,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45
        ]
    },
    {
        "name": "3pattern__0_V-033_A00.mid",
        "valence": "",
        "arousal": 2,
        "sequence": [
            41,
            0,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41,
            41
        ]
    },
    {
        "name": "pattern_0_V-067_A-033.mid",
        "valence": 1,
        "arousal": 2,
        "sequence": [
            57,
            57,
            60,
            57,
            57,
            0,
            0,
            57,
            0,
            57,
            0,
            45,
            45,
            57,
            60,
            0
        ]
    },
    {
        "name": "3pattern__0_V10_A-067.mid",
        "valence": "",
        "arousal": 6,
        "sequence": [
            39,
            0,
            39,
            0,
            39,
            0,
            39,
            0,
            0,
            0,
            0,
            44,
            0,
            0,
            0,
            37
        ]
    },
    {
        "name": "2pattern_0_V00_A00.mid",
        "valence": 3,
        "arousal": 3,
        "sequence": [
            60,
            60,
            60,
            60,
            62,
            62,
            62,
            62,
            60,
            60,
            60,
            65,
            65,
            65,
            65,
            65
        ]
    },
    {
        "name": "3pattern__0_V-10_A-067.mid",
        "valence": "",
        "arousal": 0,
        "sequence": [
            58,
            58,
            0,
            58,
            0,
            58,
            58,
            0,
            58,
            0,
            58,
            58,
            58,
            55,
            56,
            55
        ]
    },
    {
        "name": "pattern_0_V033_A-10.mid",
        "valence": 4,
        "arousal": 0,
        "sequence": [
            44,
            44,
            44,
            44,
            44,
            44,
            0,
            37,
            37,
            37,
            37,
            37,
            37,
            37,
            37,
            37
        ]
    },
    {
        "name": "3pattern__0_V067_A067.mid",
        "valence": "",
        "arousal": 5,
        "sequence": [
            73,
            66,
            66,
            69,
            66,
            54,
            42,
            42,
            42,
            42,
            42,
            42,
            42,
            42,
            42,
            42
        ]
    },
    {
        "name": "2pattern_0_V-033_A00.mid",
        "valence": 2,
        "arousal": 3,
        "sequence": [
            50,
            50,
            57,
            68,
            57,
            50,
            43,
            43,
            45,
            43,
            43,
            42,
            49,
            44,
            44,
            44
        ]
    },
    {
        "name": "3pattern__0_V-067_A067.mid",
        "valence": "",
        "arousal": 1,
        "sequence": [
            51,
            51,
            0,
            0,
            0,
            0,
            0,
            54,
            54,
            47,
            47,
            47,
            0,
            0,
            0,
            40
        ]
    },
    {
        "name": "2pattern_0_V067_A067.mid",
        "valence": 5,
        "arousal": 5,
        "sequence": [
            56,
            56,
            56,
            56,
            56,
            56,
            56,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V-10_A067.mid",
        "valence": 0,
        "arousal": 5,
        "sequence": [
            25,
            25,
            25,
            0,
            25,
            28,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            33
        ]
    },
    {
        "name": "2pattern_0_V-10_A067.mid",
        "valence": 0,
        "arousal": 5,
        "sequence": [
            34,
            34,
            34,
            34,
            34,
            34,
            31,
            31,
            31,
            38,
            38,
            38,
            31,
            29,
            29,
            29
        ]
    },
    {
        "name": "pattern_0_V067_A-067.mid",
        "valence": 5,
        "arousal": 1,
        "sequence": [
            58,
            63,
            58,
            63,
            0,
            58,
            67,
            58,
            67,
            63,
            67,
            0,
            68,
            63,
            68,
            56
        ]
    },
    {
        "name": "3pattern__0_V-067_A-033.mid",
        "valence": "",
        "arousal": 1,
        "sequence": [
            55,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            55,
            0,
            0,
            55,
            55,
            0
        ]
    },
    {
        "name": "3pattern__0_V00_A067.mid",
        "valence": "",
        "arousal": 3,
        "sequence": [
            54,
            59,
            54,
            54,
            54,
            54,
            54,
            54,
            54,
            54,
            0,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V-033_A067.mid",
        "valence": 2,
        "arousal": 5,
        "sequence": [
            50,
            0,
            54,
            0,
            66,
            47,
            47,
            47,
            47,
            59,
            47,
            47,
            47,
            59,
            59,
            63
        ]
    },
    {
        "name": "pattern_0_V10_A-067.mid",
        "valence": 6,
        "arousal": 1,
        "sequence": [
            57,
            50,
            0,
            57,
            0,
            0,
            0,
            0,
            0,
            50,
            0,
            57,
            0,
            0,
            0,
            0
        ]
    },
    {
        "name": "pattern_0_V10_A00.mid",
        "valence": 6,
        "arousal": 3,
        "sequence": [
            43,
            43,
            43,
            50,
            43,
            43,
            43,
            43,
            43,
            43,
            50,
            46,
            46,
            44,
            46,
            44
        ]
    },
    {
        "name": "pattern_0_V-10_A-033.mid",
        "valence": 0,
        "arousal": 2,
        "sequence": [
            57,
            45,
            0,
            45,
            0,
            45,
            33,
            33,
            33,
            33,
            33,
            33,
            33,
            50,
            0,
            50
        ]
    },
    {
        "name": "pattern_0_V-10_A-10.mid",
        "valence": 0,
        "arousal": 0,
        "sequence": [
            63,
            61,
            0,
            60,
            0,
            58,
            0,
            0,
            0,
            0,
            0,
            63,
            60,
            61,
            0,
            60
        ]
    },
    {
        "name": "3pattern__0_V067_A00.mid",
        "valence": "",
        "arousal": 5,
        "sequence": [
            65,
            0,
            57,
            0,
            0,
            62,
            57,
            62,
            55,
            60,
            55,
            55,
            48,
            48,
            48,
            48
        ]
    },
    {
        "name": "2pattern_0_V-10_A033.mid",
        "valence": 0,
        "arousal": 4,
        "sequence": [
            62,
            62,
            62,
            0,
            67,
            0,
            67,
            0,
            67,
            67,
            0,
            67,
            64,
            0,
            67,
            67
        ]
    }
];

function getMatchingSequences(valence, arousal) {
    const matchingSequences = sequences.filter(sequence => 
        sequence.valence === valence && sequence.arousal === arousal
    );
    
    if (matchingSequences.length > 0) {
        if (matchingSequences.length === 1) {
            return matchingSequences[0];
        } else {
            const randomIndex = Math.floor(Math.random() * matchingSequences.length);
            return matchingSequences[randomIndex];
        }
    } else {
        return null; // or handle no matches found case as needed
    }
}

module.exports = { sequences, getMatchingSequences };
